//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class joblightEntities : DbContext
    {
        public joblightEntities()
            : base("name=joblightEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TB_APPJOBMAPPER> TB_APPJOBMAPPER { get; set; }
        public DbSet<TB_APPLICATIONS> TB_APPLICATIONS { get; set; }
        public DbSet<TB_APPLICATIONSTATUS> TB_APPLICATIONSTATUS { get; set; }
        public DbSet<TB_ARTICLES> TB_ARTICLES { get; set; }
        public DbSet<TB_BRANDING> TB_BRANDING { get; set; }
        public DbSet<TB_CANDIDATES> TB_CANDIDATES { get; set; }
        public DbSet<TB_CATEGORIES> TB_CATEGORIES { get; set; }
        public DbSet<TB_CATEGORYTOTERM> TB_CATEGORYTOTERM { get; set; }
        public DbSet<TB_DOCUMENTS> TB_DOCUMENTS { get; set; }
        public DbSet<TB_EMAILRESPONSE> TB_EMAILRESPONSE { get; set; }
        public DbSet<TB_EMAILRESPONSETERMS> TB_EMAILRESPONSETERMS { get; set; }
        public DbSet<TB_EMAILTEMPLATES> TB_EMAILTEMPLATES { get; set; }
        public DbSet<TB_EMAILTYPES> TB_EMAILTYPES { get; set; }
        public DbSet<TB_JOBS> TB_JOBS { get; set; }
        public DbSet<TB_JOBTABLE> TB_JOBTABLE { get; set; }
        public DbSet<TB_JOBVIEWS> TB_JOBVIEWS { get; set; }
        public DbSet<TB_RECRUITERS> TB_RECRUITERS { get; set; }
        public DbSet<TB_RECUSERMAPPER> TB_RECUSERMAPPER { get; set; }
        public DbSet<TB_SPAMREPORT> TB_SPAMREPORT { get; set; }
        public DbSet<TB_SUBSCRIPTIONS> TB_SUBSCRIPTIONS { get; set; }
        public DbSet<TB_TERMS> TB_TERMS { get; set; }
        public DbSet<TB_TERMSLIST> TB_TERMSLIST { get; set; }
        public DbSet<TB_USERS> TB_USERS { get; set; }
        public DbSet<TB_VERSION> TB_VERSION { get; set; }
        public DbSet<VW_AGGREGATEDMPAGE> VW_AGGREGATEDMPAGE { get; set; }
        public DbSet<VW_AGGREGATEDMULTI> VW_AGGREGATEDMULTI { get; set; }
        public DbSet<VW_GETALLREC> VW_GETALLREC { get; set; }
        public DbSet<VW_GETAPP> VW_GETAPP { get; set; }
        public DbSet<VW_GETDETAILSPAGES> VW_GETDETAILSPAGES { get; set; }
        public DbSet<VW_GETJOBS> VW_GETJOBS { get; set; }
        public DbSet<VW_GETJOBSARCH> VW_GETJOBSARCH { get; set; }
        public DbSet<VW_GETJOBSARCHIVED> VW_GETJOBSARCHIVED { get; set; }
        public DbSet<VW_GETJOBSSINGLE> VW_GETJOBSSINGLE { get; set; }
        public DbSet<VW_GETJOBSSINGLEARCH> VW_GETJOBSSINGLEARCH { get; set; }
        public DbSet<VW_GETMYAPPS> VW_GETMYAPPS { get; set; }
        public DbSet<VW_GETSUBJECTEMAILAPPS> VW_GETSUBJECTEMAILAPPS { get; set; }
        public DbSet<VW_GETUSERCANS> VW_GETUSERCANS { get; set; }
        public DbSet<VW_JOBPOSTEDVIEW> VW_JOBPOSTEDVIEW { get; set; }
        public DbSet<VW_JOBSOUTMAIL> VW_JOBSOUTMAIL { get; set; }
        public DbSet<VW_JOBTORECRUITER> VW_JOBTORECRUITER { get; set; }
        public DbSet<VW_RECARTICLES> VW_RECARTICLES { get; set; }
        public DbSet<VW_RECUSERS> VW_RECUSERS { get; set; }
        public DbSet<VW_SUBREC> VW_SUBREC { get; set; }
    }
}
