//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_APPLICATIONSTATUS
    {
        public int IDTB_APPLICATIONSTATUS { get; set; }
        public Nullable<int> AAPPLICATIONSTATUS { get; set; }
        public string STERM { get; set; }
    }
}
