//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_APPLICATIONS
    {
        public string IDAPPLICATIONS { get; set; }
        public string LICANDIDATEID { get; set; }
        public Nullable<System.DateTime> DTENTERED { get; set; }
        public string AFIRSTNAME { get; set; }
        public string ALASTNAME { get; set; }
        public Nullable<System.DateTime> ADATEOFBIRTH { get; set; }
        public string APROFILESUMMARY { get; set; }
        public string DOCUMENTID { get; set; }
        public string AAPPLICATIONEMAIL { get; set; }
        public Nullable<int> AAPPLICATIONSTATUS { get; set; }
        public Nullable<System.DateTime> DTSTATUSCHANGED { get; set; }
    }
}
