//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_BRANDING
    {
        public int IDTB_BRANDING { get; set; }
        public string KPINAME { get; set; }
        public string KPIVALUE { get; set; }
    }
}
