//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_DOCUMENTS
    {
        public string DOCUMENTID { get; set; }
        public string DOCUMENTNAME { get; set; }
        public string DOC_DATA { get; set; }
        public string DOC_URL { get; set; }
    }
}
