//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_EMAILTEMPLATES
    {
        public int IDEMAILTEMPLATES { get; set; }
        public string EHEADER { get; set; }
        public string EDESCRIPTION { get; set; }
        public string EFOOTER { get; set; }
        public string ETEMPLATECHKID { get; set; }
    }
}
