//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_EMAILRESPONSETERMS
    {
        public int IDEMAILRESPONSETERMS { get; set; }
        public Nullable<int> IDEMAILRESPONSE { get; set; }
        public Nullable<int> CATID { get; set; }
        public Nullable<int> TERMID { get; set; }
    }
}
