//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_SPAMREPORT
    {
        public string IDTB_SPAMREPORT { get; set; }
        public Nullable<int> SPAMINDEX { get; set; }
        public string SPAMREASON { get; set; }
        public Nullable<System.DateTime> DTENTERED { get; set; }
        public string IPUSER { get; set; }
        public string USERAGENTS { get; set; }
        public string JOBID { get; set; }
    }
}
