//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_USERS
    {
        public string IDUSERS { get; set; }
        public Nullable<int> UUSERTYPE { get; set; }
        public string UUSERNAME { get; set; }
        public string UPASSWORD { get; set; }
        public string UPASSWORDHINT { get; set; }
        public string UFIRSTNAME { get; set; }
        public string ULASTNAME { get; set; }
        public Nullable<int> UISPRIMARY { get; set; }
        public string UCANDIDATEID { get; set; }
        public string UACTIVATION { get; set; }
    }
}
