//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_AGGREGATEDMULTI
    {
        public Nullable<decimal> APPLICATIONVOLUME { get; set; }
        public string STERM { get; set; }
        public string IDJOBS { get; set; }
        public string STITLE { get; set; }
        public string SCATEGORY { get; set; }
        public string SSHORTDESCRIPTION { get; set; }
        public string SFREETEXT { get; set; }
        public string SDESCRIPTION { get; set; }
        public Nullable<System.DateTime> DTENTEREDDATE { get; set; }
        public string SSALARYTEXT { get; set; }
        public Nullable<int> SMINSAL { get; set; }
        public string EMPLOYEEID { get; set; }
        public int TERMID { get; set; }
        public Nullable<int> SMAXSAL { get; set; }
    }
}
