//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_GETUSERCANS
    {
        public string IDUSERS { get; set; }
        public Nullable<int> UUSERTYPE { get; set; }
        public string UUSERNAME { get; set; }
        public string UPASSWORD { get; set; }
        public string UPASSWORDHINT { get; set; }
        public string UFIRSTNAME { get; set; }
        public string ULASTNAME { get; set; }
        public Nullable<int> UISPRIMARY { get; set; }
        public string UCANDIDATEID { get; set; }
        public string IDCANDIDATES { get; set; }
        public string CCANDIDATENAME { get; set; }
        public string CFIRSTNAME { get; set; }
        public Nullable<System.DateTime> CDATEOFBIRTH { get; set; }
        public string CLASTNAME { get; set; }
        public string CADDRESS1 { get; set; }
        public string CADDRESS2 { get; set; }
        public string CADDRESS3 { get; set; }
        public string CTOWN { get; set; }
        public string CCOUNTY { get; set; }
        public string CPOSTCODE { get; set; }
        public string CHOMEPHONE { get; set; }
        public string CWORKPHONE { get; set; }
        public Nullable<System.DateTime> CDTENTERED { get; set; }
        public string CCOUNTRY { get; set; }
    }
}
