//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_GETAPP
    {
        public string IDJOBS { get; set; }
        public string STITLE { get; set; }
        public string SSHORTDESCRIPTION { get; set; }
        public string SDESCRIPTION { get; set; }
        public string COMPLETEURL { get; set; }
        public Nullable<System.DateTime> DTENTEREDDATE { get; set; }
        public string SSALARYTEXT { get; set; }
        public Nullable<int> SMINSAL { get; set; }
        public Nullable<int> SMAXSAL { get; set; }
        public string SREF { get; set; }
        public string SFREETEXT { get; set; }
        public Nullable<System.DateTime> SJOBSTARTDATE { get; set; }
        public Nullable<System.DateTime> SJOBENDDATE { get; set; }
        public string IDAPPLICATIONS { get; set; }
        public string LICANDIDATEID { get; set; }
        public Nullable<System.DateTime> DTENTERED { get; set; }
        public string AFIRSTNAME { get; set; }
        public string ALASTNAME { get; set; }
        public Nullable<System.DateTime> ADATEOFBIRTH { get; set; }
        public string APROFILESUMMARY { get; set; }
        public string DOCUMENTID { get; set; }
        public string AAPPLICATIONEMAIL { get; set; }
        public string EMPID { get; set; }
        public string SRECRUITERNAME { get; set; }
    }
}
