//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_GETMYAPPS
    {
        public string IDAPPLICATIONS { get; set; }
        public string SRECRUITERNAME { get; set; }
        public string APPLICATIONSTATUS { get; set; }
        public string STITLE { get; set; }
        public string LICANDIDATEID { get; set; }
        public Nullable<System.DateTime> DTENTERED { get; set; }
        public string AFIRSTNAME { get; set; }
        public string ALASTNAME { get; set; }
        public string APROFILESUMMARY { get; set; }
        public string UUSERNAME { get; set; }
        public string IDCANDIDATES { get; set; }
        public string CCANDIDATENAME { get; set; }
        public string CFIRSTNAME { get; set; }
        public string CLASTNAME { get; set; }
        public string IDUSERS { get; set; }
    }
}
