//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_SUBREC
    {
        public string SRECRUITERNAME { get; set; }
        public string MXARTICLEDATA { get; set; }
        public Nullable<decimal> MXIDJOBS { get; set; }
        public string MXARTICLENAME { get; set; }
        public string EMPID { get; set; }
        public string MXARTICLEID { get; set; }
    }
}
