//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_JOBVIEWS
    {
        public string IDJOBVIEWS { get; set; }
        public string EMPID { get; set; }
        public Nullable<System.DateTime> DTENTERED { get; set; }
        public Nullable<int> JVIEWTYPE { get; set; }
    }
}
