//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_RECRUITERS
    {
        public string EMPID { get; set; }
        public string SRECRUITERNAME { get; set; }
        public string SADDRESS1 { get; set; }
        public string SADDRESS2 { get; set; }
        public string SADDRESS3 { get; set; }
        public string STOWN { get; set; }
        public string SCOUNTY { get; set; }
        public string SCOUNTRY { get; set; }
        public string SPOSTCODE { get; set; }
        public string SEMAILADDRESS { get; set; }
        public string SWEBSITE { get; set; }
        public string SDESCRIPTION { get; set; }
        public string SCOMPLETEDESC { get; set; }
        public Nullable<System.DateTime> SDTENTERED { get; set; }
        public Nullable<int> SENTEREDBYID { get; set; }
        public Nullable<int> SISFEATURED { get; set; }
        public string SARTICLEID { get; set; }
        public Nullable<int> SISACTIVE { get; set; }
    }
}
