//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_GETDETAILSPAGES
    {
        public string IDJOBS { get; set; }
        public Nullable<int> MINRANGE { get; set; }
        public Nullable<int> MAXRANGE { get; set; }
        public int TERMID { get; set; }
        public Nullable<int> CATID { get; set; }
        public string STERM { get; set; }
    }
}
