//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_GETALLREC
    {
        public string EMPID { get; set; }
        public string SCOMPLETEDESC { get; set; }
        public string SDESCRIPTION { get; set; }
        public string MXARTICLEDATA { get; set; }
        public string SRECRUITERNAME { get; set; }
        public string SWEBSITE { get; set; }
        public string SEMAILADDRESS { get; set; }
        public Nullable<decimal> MXIDJOBS { get; set; }
    }
}
