//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_RECARTICLES
    {
        public string EMPID { get; set; }
        public string SRECRUITERNAME { get; set; }
        public string SARTICLEID { get; set; }
        public string ARTICLENAME { get; set; }
        public string ARTICLE_DATA { get; set; }
    }
}
